version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  assignees:
  - Nyoho
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.6
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@babel/highlight"
    versions:
    - 7.10.4
  - dependency-name: "@types/yargs-parser"
    versions:
    - 15.0.0
